version: 2

enable-beta-ecosystems: true
updates:
- package-ecosystem: "uv" 
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
  - codl
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
