version: 2
updates:
#- package-ecosystem: pip
#  allow: 
#    - dependency-type: direct
#  directory: "/"
#  schedule:
#    interval: monthly
#  open-pull-requests-limit: 10
#  assignees:
#  - codl
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
