[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name="mastodon-apod"
description="APOD bot for mastodon"
maintainers=[
    {name="codl", email="codl@codl.fr"},
]
dependencies = [
	"beautifulsoup4",
	"ananas>=1.1.0",
	"mastodon.py>=1.8.1",
	"requests",
	"pillow",
]
requires-python = ">=3.10"
version = "0.1"

[tool.setuptools]
#packages = []

[tool.black]
line-length = 89

[tool.isort]
profile = "black"
line_length = 89
