name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: "pipenv"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv sync -d --system
    - name: Test with pytest
      run: |
        python -m pytest
