name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt dev-requirements.txt
    - name: Install package
      run: |
        pip install .
    - name: Test with pytest
      run: |
        python -m pytest
