name: Run tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy: 
      matrix:
        python-version: ["3.13", "3.12", "3.11", "3.10"]


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-suffix: ${{ matrix.python-version }}
    - name: Set up python ${{ matrix.python-version }}
      run: |
        uv venv --python=${{ matrix.python-version }}
    - name: Install dependencies and package
      run: |
        uv sync --all-extras --frozen
    - name: Test with pytest
      run: |
        uv run --frozen python -m pytest
